// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using ServerSide.DAL;
using System;

namespace ServerSide.Migrations
{
    [DbContext(typeof(TaskListContext))]
    [Migration("20180428231411_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("ServerSide.DAL.Models.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int?>("TodoId");

                    b.HasKey("Id");

                    b.HasIndex("TodoId");

                    b.ToTable("Attachment");
                });

            modelBuilder.Entity("ServerSide.DAL.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateCreate");

                    b.Property<string>("Heading")
                        .IsRequired();

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.ToTable("Todo");
                });

            modelBuilder.Entity("ServerSide.DAL.Models.Attachment", b =>
                {
                    b.HasOne("ServerSide.DAL.Models.Todo", "Todo")
                        .WithMany("Attachments")
                        .HasForeignKey("TodoId");
                });
#pragma warning restore 612, 618
        }
    }
}
